tmp_dir: "/tmp"
mysql:
  collation_server: "utf8mb4_unicode_ci"
  character_set_server: "utf8mb4"
  max_heap_table_size: "128M"
  tmp_table_size: "64M"
  join_buffer_size: "64M"
  innodb_file_format: "Barracuda"
  innodb_large_prefix: "1"
  innodb_buffer_pool_size: "1GB"
  innodb_buffer_pool_instances: "10"
  innodb_flush_log_at_timeout: "3"
  innodb_read_io_threads: "32"
  innodb_write_io_threads: "16"
  innodb_io_capacity: "5000"
  innodb_io_capacity_max: "10000"
  user: "cacti"
  user_password: "cacti"
  database: "cacti"
  config: "/etc/mysql/mariadb.conf.d/50-server.cnf"
cacti:
  url: "https://www.cacti.net/downloads/cacti-latest.tar.gz"
  name: "cacti-latest.tar.gz"
  config: "/opt/cacti/include/config.php"
  log: "/opt/cacti/log/cacti.log"
  work_dir: "/opt/cacti"
  sql: "cacti.sql"